#!/bin/bash

# Take input with defining variable
read -p "Which test would you like to run?
1. TestAddAndDeleteToDataBase 
2. TestGetLonLatFromZip  
3. TestDateTimeConversions
4. TestUpdateToDataBase
5. All
enter number:" answer

if [ $answer == "1" ];
then
    python3 DataBaseHelperFunctionsTestFixture.py TestAddAndDeleteToDataBase
elif [ $answer == "2" ];
then
    python3 DataBaseHelperFunctionsTestFixture.py TestGetLonLatFromZip
elif [ $answer == "3" ];
then
    python3 DataBaseHelperFunctionsTestFixture.py TestDateTimeConversions
elif [ $answer == "4" ];
then
    python3 DataBaseHelperFunctionsTestFixture.py TestUpdateToDataBase
elif [ $answer == "5" ];
then 
    python3 DataBaseHelperFunctionsTestFixture.py
else
    echo "Not a valid choice"
fi