#!/bin/bash

###########################
# Last updated on 06/26/2022
#
###########################

# Take input with defining variable
read -p "Which test would you like to run?
1. Run Code Coverage
2. Run All Test
3. TestAddAndDeleteToDataBase 
4. TestGetLonLatFromZip  
5. TestDateTimeConversions
6. TestUpdateToDataBase
7. TestGetDBEntryFromLatLong
enter number:" answer

if [ $answer == "1" ];
then
    coverage run DataBaseHelperFunctionsTestFixture.py
    
elif [ $answer == "2" ];
then
    python3 DataBaseHelperFunctionsTestFixture.py

elif [ $answer == "3" ];
then
    python3 DataBaseHelperFunctionsTestFixture.py TestAddAndDeleteToDataBase

elif [ $answer == "4" ];
then
    python3 DataBaseHelperFunctionsTestFixture.py TestGetLonLatFromZip

elif [ $answer == "5" ];
then 
    python3 DataBaseHelperFunctionsTestFixture.py TestDateTimeConversions

elif [ $answer == "6" ];
then 
    python3 DataBaseHelperFunctionsTestFixture.py TestUpdateToDataBase

elif [ $answer == "7" ];
then 
    python3 DataBaseHelperFunctionsTestFixture.py TestGetDBEntryFromLatLong

else
    echo "Not a valid choice"
fi